### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by mvdan** [hackupc/hackupc#6]
To keep our sanity. At least to check for html/css/js syntax errors.

Any ideas @dasilvacontin @Towerthousand?

**Comment by mvdan** [comment]
Done. Right now it's just the default setup, which I think tests the build. Feel free to improve it.

**Comment by dasilvacontin** [comment]
I'll probably add the [standard](https://github.com/feross/standard) js linter, since it's the style I'm using.

**Comment by mvdan** [comment]
Cool!
